### ISSUE TITLE
Some answer .yaml and .json pairs fail to show on TPZ

### ISSUE THREAD

**Issue by riebling** [11-791SoftwareEngineeringForIT/Project0#2]
In the example in this repository, there are 3 questions, labeled q1, q2, q3 with types Number, Number, String. This works fine.

If I edit the files (both .yaml and .json) such that there is only 1 question of type String,
labeled q4, TPZ AGS seems to go out to lunch: nothing shows up after submissions,
after waiting 5 minutes, etc.

This is the exact same string that works, when it's q3. Changing it's label to q4 (in both `output.json` and `reference.yaml`), and removing all the other questions - causes submissions to fail to appear.

Here is the example that fails for me:

reference.yaml:
```
# Supported answer types:
# String Int Decimal Range Regex Json
#
# code attribute:
# double-quoted style (\ and " must be escaped by \,
# newlines can be inserted with a literal \n sequence,
# lines can be concatenated without spaces with trailing \)
# trailing spaces are ignored, can be used freely as indentation
#
# answer/secret attribute with JSON/CSV:
# single-quoted style (literal ' must be escaped to doubled '', no special characters)
# trailing spaces are ignored, can be used freely as indentation
# \n is needed as newline
---
metadata:
  secret_data: False
  student_output: "output.json"
questions:
- id: q4
  type: String
  answer: "A very much longer string with lots and lots of words in it\nA second line of text after the newline"
  score: 5
  scoreType: Number
```
output.json:
```
{
 "q4":"A very much longer string with lots and lots of words in it\nA second line of text after the newline"
}
```

I am not sure if the bug is a result of using the label "q4" (labels can be arbitrary strings, right?) or, more likely, something about the fact there is only a single question, or something subtle like that there is only one question AND it happens to be of type String. I haven't tested all the permutations.
